### ISSUE TITLE
Plugin not updating project path when directory is changed

### ISSUE THREAD

**Issue by CWood-sdf** [catgoose/do-the-needful#8]
I personally use a start screen that I made ([spaceport](https://github.com/CWood-sdf/spaceport.nvim)) for getting to my projects. Under the hood, it changes neovim's cwd so that I can get to any project. However, this functionality breaks this plugin because it sets the project .tasks.json path to whatever the cwd of neovim was when it was opened, not the cwd that spaceport sets it to when entering a project

If you want me to write a pr for this issue to save your time, I could definitely do that

**Comment by catgoose** [comment]
Sure, if you write a PR I will take a look at it.
